import { IUtilizador } from '../../shared/i-utilizador';

const DataDummy2: IUtilizador = {
  id: 100,
  email: 'tony@gmail.com',
  idade: 42,
  ativo: true,
  dataRegistro: new Date(),
  salario: 1000,
  departamento: 'comercial de vendas',
};

//export const DataDummy: IUtilizador = [{...DataDummy2}];
export const DataDummy: IUtilizador[] = [
    DataDummy2,
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    salario: 1000,
    departamento: 'comercial de vendas',
  },
  {
    id: 101,
    email: 'ana@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date("2023-01-05"),
    salario: 1000,
    departamento: 'dep informatico',
  },
  {
    id: 102,
    email: 'leo@gmail.com',
    idade: 20,
    ativo: true,
    dataRegistro: new Date("2025-01-01"),
    salario: 1000,
    departamento: 'dep financeiro',
  },
  {
    id: 103,
    email: 'maria@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    salario: 1000,
    departamento: 'comercial de vendas',
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    salario: 1000,
    departamento: 'comercial de vendas',
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    salario: 1000,
    departamento: 'comercial de vendas',
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    salario: 1000,
    departamento: 'comercial de vendas',
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    salario: 1000,
    departamento: 'comercial de vendas',
  },
  {
    id: 100,
    email: 'tony@gmail.com',
    idade: 42,
    ativo: true,
    dataRegistro: new Date(),
    salario: 1000,
    departamento: 'comercial de vendas',
  },
];
